name: buildbot

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          ref: 'master'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Build python CI
        run: |
          sudo apt-get -q update
          sudo apt-get install dos2unix
          pip install --upgrade pip autopep8
          ./CI/build.sh
